### ISSUE TITLE
Voxeet sample app not working

### ISSUE THREAD

**Issue by bravemaster619** [voxeet/voxeet-web-conferencekit#1]
I've signed up voxeet and got my consumer key for trials. And I added consumerKey and consumerSecret key to my VoxeetConference.js and tried to start yarn:
```
$ yarn start
```
```
yarn run v1.19.0
$ webpack-dev-server -d --hot --inline --content-base
Project is running at https://localhost:8080/
webpack output is served from /     // ...omitted from here
```
It was good at first, but when I tried to visit localhost:8080, the following errors showed and failed:
```
(node:27884) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
internal/buffer.js:940
class FastBuffer extends Uint8Array {}
^

RangeError: Invalid typed array length: -4095
    at new Uint8Array (<anonymous>)
    at new FastBuffer (internal/buffer.js:940:1)
    at Handle.onStreamRead [as onread] (internal/stream_base_commons.js:181:19)
    at Stream.<anonymous> (E:\kjy\itinerary\02_source\voxeet\node_modules\handle-thing\lib\handle.js:120:12)
    at Stream.emit (events.js:215:7)
    at endReadableNT (E:\kjy\itinerary\02_source\voxeet\node_modules\readable-stream\lib\_stream_readable.js:1010:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

My npm version is 6.11.3 and node version is 12.11.1 and yarn version is 1.19.0. Could you please tell me what is wrong?

**Comment by Energizz** [comment]
Hello, 
Can you switch your node version to v10.15.3 and try again please ? 
(You need to use the LTS version)

**Comment by bravemaster619** [comment]
Hi. I just downgraded node version to 10.15.3 and it works like a charm! But one question, what is LTS version anyway? Is it more steady? Thanks.
