### ISSUE TITLE
Works well in localhost but shows NotSupportedError when deployed to the production server

### ISSUE THREAD

**Issue by bravemaster619** [voxeet/voxeet-web-conferencekit#2]
**Uncaught (in promise) NotSupportedError: This operation is not supported on this browser**

I have customized voxeet App.js so that it loads user information (`conferenceName`, `userName`, `photoURL` and `externalId`) from cookie. It works well in localhost but when I deploy it to a server, it shows the following error:
```
voxeet.js:4683 Uncaught (in promise) NotSupportedError: This operation is not supported on this browser
    at new BrowserError (http://tk2-237-28163.vs.sakura.ne.jp/module/itinerary/widgets/voxeet.js:4683:13486)
    at new BrowserNotSupportedError (http://tk2-237-28163.vs.sakura.ne.jp/module/itinerary/widgets/voxeet.js:4683:15577)
    at Function.value (http://tk2-237-28163.vs.sakura.ne.jp/module/itinerary/widgets/voxeet.js:4678:142252)
    at VoxeetSdk.value (http://tk2-237-28163.vs.sakura.ne.jp/module/itinerary/widgets/voxeet.js:4672:7889)
    at http://tk2-237-28163.vs.sakura.ne.jp/module/itinerary/widgets/voxeet.js:4130:32789
    at Object.dispatch (http://tk2-237-28163.vs.sakura.ne.jp/module/itinerary/widgets/voxeet.js:4112:18)
    at http://tk2-237-28163.vs.sakura.ne.jp/module/itinerary/widgets/voxeet.js:4148:165660
```
**Minimalistic code (recommended)**

```
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import ReactDOM from 'react-dom'
import VoxeetConference from './VoxeetConference'
import Cookie from 'react-cookies'
class App extends Component {

  constructor(props) {
      super(props);
      this.state = {
        isSubmit: true,
        users: [
          
        ],
        form : {
          conferenceName: Cookie.load('itn_tour_name'),
          userName: Cookie.load("itn_user_name"),
          photoURL: Cookie.load("itn_user_avatar"),
          externalId: Cookie.load("itn_user_id")
        }
      }
      this.handleChange = this.handleChange.bind(this)
      this.handleChangeSelect = this.handleChangeSelect.bind(this)
  }
  // ... rest omitted ...
```

**Specifications**

  - Device: Desktop
  - OS: Windows 10
  - Platform: Google Chrome 77.0.3865.90, Mozilla Firefox 69.0.3 (64-bit)
  - Version:
    - @voxeet/voxeet-web-sdk 1.8.6
    - @voxeet/react-components 0.31.0
    - node 10.15.3
    - react 16.7.0
    - react-cookies 0.1.1

**Comment by bravemaster619** [comment]
I depoloyed it to `http` localhost. `navigator.mediaDevices` returned `undefined`. For more information please check: [Why does navigator.mediaDevices work differently in localhost and server?](https://stackoverflow.com/questions/58533341/why-does-navigator-mediadevices-work-differently-in-localhost-and-server)
